//! Centralized error handling.
//!
//! Provides the `AppError` type and translates application errors into
//! standard-compliant RFC 7807 HTTP Problem Details responses.

use axum::{
    Json,
    http::{StatusCode, header},
    response::{IntoResponse, Response},
};
use sea_orm::SqlErr;
use serde::Serialize;
use serde_json::json;
use thiserror::Error;
use utoipa::ToSchema;

/// One row that's stopping a delete/update from proceeding.
///
/// Carried on [`AppError::ConflictWithReferences`] so the frontend can show
/// the caller exactly what's in the way (e.g. "used by 2 events: ...")
/// instead of a bare "conflict" message.
#[derive(Debug, Serialize, ToSchema)]
pub struct BlockingReference {
    /// The kind of thing blocking the action, e.g. `"event"`.
    pub resource: String,
    /// The blocking row's id.
    pub id: i64,
    /// Human-readable label for that row (its title/name), for display.
    pub label: String,
}

/// The standard RFC 7807 Problem Details representation for HTTP API errors.
#[derive(Debug, Serialize, ToSchema)]
pub struct ProblemDetails {
    /// A URI reference that identifies the problem type.
    #[serde(rename = "type")]
    pub type_uri: &'static str,
    /// A short, human-readable summary of the problem type.
    pub title: &'static str,
    /// The HTTP status code generated by the origin server for this occurrence.
    pub status: u16,
    /// A human-readable explanation specific to this occurrence of the problem.
    pub detail: String,
    /// A URI reference that identifies the specific occurrence of the problem.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
    /// Optional parameter validation errors or specific metadata.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invalid_params: Option<serde_json::Value>,
}

/// Centralized application error registry.
#[derive(Debug, Error)]
pub enum AppError {
    /// Error triggered by the `SeaORM` database layer.
    #[error("Database error: {0}")]
    Database(#[from] sea_orm::DbErr),

    /// Error indicating a requested resource was not found.
    #[error("Resource not found: {0}")]
    NotFound(String),

    /// Error indicating the client has not authenticated or token is invalid.
    #[error("Unauthorized: {0}")]
    Unauthorized(String),

    /// Error indicating the client lacks necessary permissions.
    #[error("Forbidden: {0}")]
    Forbidden(String),

    /// Error indicating client input parameters are invalid.
    #[error("Validation error: {0}")]
    Validation(String),

    /// Error indicating a request conflicts with existing state (e.g. resource already linked).
    #[error("Conflict: {0}")]
    Conflict(String),

    /// A conflict where the caller needs to see exactly what's blocking the
    /// action (e.g. deleting a comp that's still linked to live events) —
    /// carries the specific rows in the way, not just a message string.
    #[error("Conflict: {message}")]
    ConflictWithReferences {
        /// Human-readable summary of the conflict.
        message: String,
        /// The specific rows in the way, for a rich frontend list.
        references: Vec<BlockingReference>,
    },

    /// Error indicating an upstream third-party service (e.g. Albion Online API) failed or is unreachable.
    #[error("Upstream service error: {0}")]
    UpstreamService(String),

    /// Fallback error representing an unhandled internal server issue.
    #[error("Internal server error: {0}")]
    Internal(String),
}

impl IntoResponse for AppError {
    fn into_response(self) -> Response {
        let (status, type_uri, title, detail, invalid_params) = match self {
            Self::Database(err) => {
                // A constraint violation is a client-facing conflict, not a
                // server fault — map it to 409 with an honest-but-generic
                // message instead of a bare 500 with the raw driver text.
                // This is the safety net for every module that doesn't (yet)
                // pre-check its own delete/update against referencing rows;
                // callers that want the rich per-reference list return
                // `ConflictWithReferences` themselves before ever reaching
                // the database.
                match err.sql_err() {
                    Some(SqlErr::ForeignKeyConstraintViolation(_)) => (
                        StatusCode::CONFLICT,
                        "/errors/conflict",
                        "Conflict",
                        "This item can't be removed or changed because something else still refers to it.".to_string(),
                        None,
                    ),
                    Some(SqlErr::UniqueConstraintViolation(_)) => (
                        StatusCode::CONFLICT,
                        "/errors/conflict",
                        "Conflict",
                        "That value is already in use.".to_string(),
                        None,
                    ),
                    _ => {
                        // Every other `DbErr` is a genuine server fault, and its
                        // `Display` carries the raw driver text — SQL, table and
                        // column names, and on this multi-tenant deployment the
                        // Postgres schema name, which doubles as a tenant
                        // identifier. Log it for operators; the client gets an
                        // honest-but-generic message instead.
                        tracing::error!(error = %err, "unclassified database error");
                        (
                            StatusCode::INTERNAL_SERVER_ERROR,
                            "/errors/database-error",
                            "Database Error",
                            "A database error occurred. Please try again, or contact support if \
                             the problem persists."
                                .to_string(),
                            None,
                        )
                    }
                }
            }
            Self::NotFound(msg) => (
                StatusCode::NOT_FOUND,
                "/errors/not-found",
                "Resource Not Found",
                msg,
                None,
            ),
            Self::Unauthorized(msg) => (
                StatusCode::UNAUTHORIZED,
                "/errors/unauthorized",
                "Unauthorized Access",
                msg,
                None,
            ),
            Self::Forbidden(msg) => (
                StatusCode::FORBIDDEN,
                "/errors/forbidden",
                "Access Forbidden",
                msg,
                None,
            ),
            Self::Validation(msg) => (
                StatusCode::BAD_REQUEST,
                "/errors/validation-error",
                "Validation Error",
                msg,
                None,
            ),
            Self::Conflict(msg) => (
                StatusCode::CONFLICT,
                "/errors/conflict",
                "Conflict",
                msg,
                None,
            ),
            Self::ConflictWithReferences {
                message,
                references,
            } => (
                StatusCode::CONFLICT,
                "/errors/conflict",
                "Conflict",
                message,
                Some(json!({ "blocking_references": references })),
            ),
            Self::UpstreamService(msg) => (
                StatusCode::BAD_GATEWAY,
                "/errors/upstream-service-error",
                "Upstream Service Error",
                msg,
                None,
            ),
            Self::Internal(msg) => (
                StatusCode::INTERNAL_SERVER_ERROR,
                "/errors/internal-error",
                "Internal Server Error",
                msg,
                None,
            ),
        };

        let problem = ProblemDetails {
            type_uri,
            title,
            status: status.as_u16(),
            detail,
            instance: None,
            invalid_params,
        };

        (
            status,
            [(header::CONTENT_TYPE, "application/problem+json")],
            Json(problem),
        )
            .into_response()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::body::to_bytes;

    async fn problem_of(err: AppError) -> ProblemDetailsJson {
        let response = err.into_response();
        let status = response.status();
        let bytes = to_bytes(response.into_body(), usize::MAX)
            .await
            .expect("response body reads");
        let json: serde_json::Value =
            serde_json::from_slice(&bytes).expect("problem+json body parses");
        ProblemDetailsJson {
            status,
            detail: json["detail"].as_str().expect("detail is a string").to_owned(),
        }
    }

    struct ProblemDetailsJson {
        status: StatusCode,
        detail: String,
    }

    /// An unclassified `DbErr` (not a FK/unique violation `sea_orm` can name —
    /// `DbErr::Custom`, `RecordNotFound`, `Conn`, `Exec`, `Query`, ... all land
    /// here, since a *classified* violation needs a live `sqlx::Error::Database`
    /// this test cannot construct outside the crate) is a genuine server
    /// fault. It must not hand the client the driver's raw text: on this
    /// multi-tenant deployment a Postgres error routinely names the schema,
    /// which doubles as a tenant identifier, plus table and column names no
    /// API consumer needs to see.
    #[tokio::test]
    async fn unclassified_database_error_hides_the_driver_message() {
        let leaky = r#"column "control.tenants.owner_discord_id" does not exist"#;
        let problem = problem_of(AppError::Database(sea_orm::DbErr::RecordNotFound(
            leaky.to_owned(),
        )))
        .await;
        assert_eq!(problem.status, StatusCode::INTERNAL_SERVER_ERROR);
        assert!(
            !problem.detail.contains("control")
                && !problem.detail.contains("tenants")
                && !problem.detail.contains("owner_discord_id"),
            "leaked driver text into a client-facing response: {}",
            problem.detail
        );
        assert!(!problem.detail.is_empty());
    }
}
