//! Centralized error handling.
//!
//! Provides the `AppError` type and translates application errors into
//! standard-compliant RFC 7807 HTTP Problem Details responses.

use axum::{
    Json,
    http::{StatusCode, header},
    response::{IntoResponse, Response},
};
use serde::Serialize;
use thiserror::Error;
use utoipa::ToSchema;

/// The standard RFC 7807 Problem Details representation for HTTP API errors.
#[derive(Debug, Serialize, ToSchema)]
pub struct ProblemDetails {
    /// A URI reference that identifies the problem type.
    #[serde(rename = "type")]
    pub type_uri: &'static str,
    /// A short, human-readable summary of the problem type.
    pub title: &'static str,
    /// The HTTP status code generated by the origin server for this occurrence.
    pub status: u16,
    /// A human-readable explanation specific to this occurrence of the problem.
    pub detail: String,
    /// A URI reference that identifies the specific occurrence of the problem.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
    /// Optional parameter validation errors or specific metadata.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invalid_params: Option<serde_json::Value>,
}

/// Centralized application error registry.
#[derive(Debug, Error)]
pub enum AppError {
    /// Error triggered by the `SeaORM` database layer.
    #[error("Database error: {0}")]
    Database(#[from] sea_orm::DbErr),

    /// Error indicating a requested resource was not found.
    #[error("Resource not found: {0}")]
    NotFound(String),

    /// Error indicating the client has not authenticated or token is invalid.
    #[error("Unauthorized: {0}")]
    Unauthorized(String),

    /// Error indicating the client lacks necessary permissions.
    #[error("Forbidden: {0}")]
    Forbidden(String),

    /// Error indicating client input parameters are invalid.
    #[error("Validation error: {0}")]
    Validation(String),

    /// Error indicating a request conflicts with existing state (e.g. resource already linked).
    #[error("Conflict: {0}")]
    Conflict(String),

    /// Error indicating an upstream third-party service (e.g. Albion Online API) failed or is unreachable.
    #[error("Upstream service error: {0}")]
    UpstreamService(String),

    /// Fallback error representing an unhandled internal server issue.
    #[error("Internal server error: {0}")]
    Internal(String),
}

impl IntoResponse for AppError {
    fn into_response(self) -> Response {
        let (status, type_uri, title, detail) = match self {
            Self::Database(ref err) => (
                StatusCode::INTERNAL_SERVER_ERROR,
                "/errors/database-error",
                "Database Error",
                err.to_string(),
            ),
            Self::NotFound(msg) => (
                StatusCode::NOT_FOUND,
                "/errors/not-found",
                "Resource Not Found",
                msg,
            ),
            Self::Unauthorized(msg) => (
                StatusCode::UNAUTHORIZED,
                "/errors/unauthorized",
                "Unauthorized Access",
                msg,
            ),
            Self::Forbidden(msg) => (
                StatusCode::FORBIDDEN,
                "/errors/forbidden",
                "Access Forbidden",
                msg,
            ),
            Self::Validation(msg) => (
                StatusCode::BAD_REQUEST,
                "/errors/validation-error",
                "Validation Error",
                msg,
            ),
            Self::Conflict(msg) => (StatusCode::CONFLICT, "/errors/conflict", "Conflict", msg),
            Self::UpstreamService(msg) => (
                StatusCode::BAD_GATEWAY,
                "/errors/upstream-service-error",
                "Upstream Service Error",
                msg,
            ),
            Self::Internal(msg) => (
                StatusCode::INTERNAL_SERVER_ERROR,
                "/errors/internal-error",
                "Internal Server Error",
                msg,
            ),
        };

        let problem = ProblemDetails {
            type_uri,
            title,
            status: status.as_u16(),
            detail,
            instance: None,
            invalid_params: None,
        };

        (
            status,
            [(header::CONTENT_TYPE, "application/problem+json")],
            Json(problem),
        )
            .into_response()
    }
}
